language: elixir

matrix:
  include:
    - elixir: 1.8.2
      otp_release:
          - 20.0
          - 21.0
          - 22.0
    - elixir: 1.9.4
      otp_release:
          - 20.0
          - 21.0
          - 22.0

script:
  - mix test

addons:
  apt:
    packages:
      - libsodium-dev
      - gcc
      - make
      - erlang-dev
